<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="USPS Reports UI testcases" duration-ms="75349" started-at="2023-03-27T07:04:47Z" finished-at="2023-03-27T07:06:02Z">
    <groups>
    </groups>
    <test name="USPS Reports" duration-ms="75349" started-at="2023-03-27T07:04:47Z" finished-at="2023-03-27T07:06:02Z">
      <class name="qa.vector.UspsCalculatorTest">
        <test-method status="PASS" signature="open()[pri:0, instance:qa.vector.UspsCalculatorTest@8e24743]" name="open" is-config="true" duration-ms="3922" started-at="2023-03-27T00:04:47Z" finished-at="2023-03-27T00:04:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open -->
        <test-method status="PASS" signature="uspsCalTest1()[pri:0, instance:qa.vector.UspsCalculatorTest@8e24743]" name="uspsCalTest1" duration-ms="18244" started-at="2023-03-27T00:04:51Z" description="Type1:Home Depot box Small - (16 in. L x 12 in. W x 12 in. D)" finished-at="2023-03-27T00:05:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- uspsCalTest1 -->
        <test-method status="PASS" signature="close()[pri:0, instance:qa.vector.UspsCalculatorTest@8e24743]" name="close" is-config="true" duration-ms="4215" started-at="2023-03-27T00:05:09Z" finished-at="2023-03-27T00:05:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- qa.vector.UspsCalculatorTest -->
      <class name="CommonUtility.SetEnvStaging">
        <test-method status="PASS" signature="SetFunEnv()[pri:0, instance:CommonUtility.SetEnvStaging@cb0ed20]" name="SetFunEnv" duration-ms="71" started-at="2023-03-27T00:04:47Z" finished-at="2023-03-27T00:04:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetFunEnv -->
      </class> <!-- CommonUtility.SetEnvStaging -->
      <class name="qa.vector.UspsCalculatorTest2">
        <test-method status="PASS" signature="open()[pri:0, instance:qa.vector.UspsCalculatorTest2@74a10858]" name="open" is-config="true" duration-ms="2698" started-at="2023-03-27T00:05:14Z" finished-at="2023-03-27T00:05:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open -->
        <test-method status="FAIL" signature="uspsCalTest2()[pri:0, instance:qa.vector.UspsCalculatorTest2@74a10858]" name="uspsCalTest2" duration-ms="17309" started-at="2023-03-27T00:05:16Z" description="Type1:Home Depot box Medium -Â  (22 in. L x 16 in. W x 15 in. D)" finished-at="2023-03-27T00:05:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Price is higher than $80 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Price is higher than $80 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at qa.vector.UspsCalculatorTest2.uspsCalTest2(UspsCalculatorTest2.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- uspsCalTest2 -->
        <test-method status="PASS" signature="close()[pri:0, instance:qa.vector.UspsCalculatorTest2@74a10858]" name="close" is-config="true" duration-ms="4209" started-at="2023-03-27T00:05:34Z" finished-at="2023-03-27T00:05:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- qa.vector.UspsCalculatorTest2 -->
      <class name="qa.vector.UspsCalculatorTest3">
        <test-method status="PASS" signature="open()[pri:0, instance:qa.vector.UspsCalculatorTest3@23fe1d71]" name="open" is-config="true" duration-ms="2151" started-at="2023-03-27T00:05:38Z" finished-at="2023-03-27T00:05:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open -->
        <test-method status="FAIL" signature="uspsCalTest3()[pri:0, instance:qa.vector.UspsCalculatorTest3@23fe1d71]" name="uspsCalTest3" duration-ms="17165" started-at="2023-03-27T00:05:40Z" description="Type3:Home Depot box Large - (28 in. L x 15 in. W x 16 in. D)" finished-at="2023-03-27T00:05:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Price is higher than $80 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Price is higher than $80 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at qa.vector.UspsCalculatorTest3.uspsCalTest3(UspsCalculatorTest3.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- uspsCalTest3 -->
        <test-method status="PASS" signature="close()[pri:0, instance:qa.vector.UspsCalculatorTest3@23fe1d71]" name="close" is-config="true" duration-ms="4196" started-at="2023-03-27T00:05:58Z" finished-at="2023-03-27T00:06:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- qa.vector.UspsCalculatorTest3 -->
    </test> <!-- USPS Reports -->
  </suite> <!-- USPS Reports UI testcases -->
</testng-results>
